### ISSUE TITLE
invalid memory address or nil pointer when failing to connect

### ISSUE THREAD

**Issue by Melvillian** [BitGo/prova#17]
My prova node is panicing when it fails to connect to a given IP. Normally the log output for a failure to connect looks like this:

```
17:30:29 2017-04-18 [DBG] CMGR: Attempting to connect to 52.8.19.84:17979 (reqid 455647)
17:30:30 2017-04-18 [DBG] CMGR: Failed to connect to 52.8.19.84:17979 (reqid 455641): dial tcp 52.8.19.84:17979: i/o timeout
17:30:30 2017-04-18 [DBG] CMGR: Attempting to connect to 52.8.19.84:17979 (reqid 455648)
17:30:56 2017-04-18 [DBG] CMGR: Failed to connect to 52.8.19.84:17979 (reqid 455642): dial tcp 52.8.19.84:17979: i/o timeout
17:30:56 2017-04-18 [DBG] CMGR: Attempting to connect to 52.8.19.84:17979 (reqid 455649)
```

However, interspersed with these correct error messages I see groups of the following error message:

```
17:30:58 2017-04-18 [DBG] CMGR: Failed to connect to %!v(PANIC=runtime error: invalid memory address or nil pointer dereference): no valid connect address
17:30:58 2017-04-18 [DBG] CMGR: Failed to connect to %!v(PANIC=runtime error: invalid memory address or nil pointer dereference): no valid connect address
17:30:58 2017-04-18 [DBG] CMGR: Failed to connect to %!v(PANIC=runtime error: invalid memory address or nil pointer dereference): no valid connect address
17:30:58 2017-04-18 [DBG] CMGR: Failed to connect to %!v(PANIC=runtime error: invalid memory address or nil pointer dereference): no valid connect address
```

This isn't causing my system to crash, or even noticeably affecting it, but it does seem to be an invalid null-pointer-exception type error

**Comment by SCDeveloper** [comment]
I have attempted to replicate on OSX Sierra with Prova without success. What operating system are you running? Was there anything specific you were attempting at the time? Any information to help replicate the issue would be welcomed :)

**Comment by spencerlievens** [comment]
Bump

Has this been resolved?

**Comment by Melvillian** [comment]
I just ran on testnet and mainnet for a while, and did not see any errors. Plus @alexbosworth mentioned out-of-band that he had written a fix for this.
