### ISSUE TITLE
Admin RPC API - dead link

### ISSUE THREAD

**Issue by rohasnagpal** [BitGo/prova#18]
This is a deadlink
https://github.com/BitGo/prova/blob/master/docs/admin-api.md

**Comment by kuzcoh** [comment]
We've made a note of this internally and this should be fixed soon. In the meantime, you can find the renamed file here: https://github.com/BitGo/prova/blob/master/docs/json_rpc_api.md

**Comment by SCDeveloper** [comment]
https://github.com/BitGo/prova/pull/21 - Issue can be closed once this is merged.

**Comment by SCDeveloper** [comment]
This can be closed.
