### ISSUE TITLE
Travis-CI

### ISSUE THREAD

**Issue by spencerlievens** [BitGo/prova#26]
Could Travis-CI be implemented on this repository as to run tests on Pull Requests and merges made?

**Comment by spencerlievens** [comment]
https://github.com/BitGo/prova/pull/27

**Comment by spencerlievens** [comment]
Travis-CI can now be enabled on this repository.

**Comment by jlopp** [comment]
Enabled and activated with https://github.com/BitGo/prova/pull/31
