### ISSUE TITLE
[Travis-CI] Unit Tests

### ISSUE THREAD

**Issue by spencerlievens** [BitGo/prova#33]
Currently Travis CI is being utilised solely for build testing and does not run the unit tests.

**Comment by spencerlievens** [comment]
Bump.

**Comment by jlopp** [comment]
Any thoughts @alexbosworth ?

**Comment by alexbosworth** [comment]
I didn't set Travis up - not sure who did, but it sounds good to make it run unit tests

**Comment by spencerlievens** [comment]
Me :P 

https://github.com/BitGo/prova/pull/27

**Comment by alexbosworth** [comment]
I don't have experience with Travis but if I get time I will look into how it works - our travis yaml doesn't look too different from btcsuite so no clues there

**Comment by spencerlievens** [comment]
Yeah they are not running unittests either I do not think, I will investigate. I will also just try adding the standard command for running unittests to the travis.yaml file and see what happens upon pushing.

**Comment by spencerlievens** [comment]
https://travis-ci.org/spencerlievens/prova/builds/307174469?utm_source=github_status&utm_medium=notification

Let's see if this works. @alexbosworth @jlopp

**Comment by spencerlievens** [comment]
Also, currently, Prova is being built with Go versions 1.6 and 1.7. I assume it would be a good idea to bump these to versions 1.8 and 1.9.

**Comment by spencerlievens** [comment]
OK @alexbosworth @jlopp I have sorted Travis tests ;)

It can be merged :D
